FROM mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye

# setup git subtree
RUN chmod +x /usr/share/doc/git/contrib/subtree/git-subtree.sh && ln -s /usr/share/doc/git/contrib/subtree/git-subtree.sh /usr/local/libexec/git-core/git-subtree