version: "3.8"

networks:
  app-network:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - SCHEMA_PATH=${SCHEMA_PATH}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    env_file: ${CODESPACE_ENV}
    command: sleep infinity
    networks:
      - app-network

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    env_file: ${POSTGRES_ENV}
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    volumes:
      - type: volume
        source: minio-data
        target: /data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - app-network
    ports:
      - 9000:9000
      - 9001:9001
volumes:
  postgres-data:
  minio-data:
  root-data:
  frontend-data:
  backend-data:
